# Generated by Django 5.1.3 on 2024-11-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_person_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
