# Generated by Django 5.1.3 on 2024-11-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_page',
            field=models.CharField(max_length=50),
        ),
    ]
